<div class="col-lg-4">
    <div class="card-box p-0">
        <div class="profile-widget text-center">
            <div class="bg-info bg-profile"></div>
            <img src="http://media2.bazaarvoice.com/images/backend-icon-215.png" class="thumb-lg img-circle img-thumbnail" alt="img">
            <h4>Detalhes técnicos</h4>
            <a href="https://github.com/marcus-campos/max-milhas-challenge" class="btn btn-sm btn-github m-t-20"><i class="fa fa-github" aria-hidden="true"></i> GitHub - Código fonte</a>
            <a href="https://github.com/marcus-campos/milhas" class="btn btn-sm btn-github m-t-20"><i class="fa fa-github" aria-hidden="true"></i> GitHub - Código fonte framework</a>
            <p class="m-t-10 text-muted p-20">
                O desafio consiste em criar uma aplicação web que seja possível cadastrar uma nova foto, ver a lista de fotos cadastradas e excluir uma foto. Todo o desafio deveria ser concluido sem uso de frameworks prontos em PHP
            </p>
            <h4>Tecnologia utilizada: </h4>
            <p class="m-t-10 text-muted p-20">
                PHP 7 <br>
                PHPUnit <br>
                SQLite3 <br>
                HTML 5 <br>
                CSS 3 <br>
                JQuery <br>
            </p>
        </div>
    </div>
</div>
<div class="col-lg-4">
    <div class="card-box p-0">
        <div class="profile-widget text-center">
            <div class="bg-custom bg-profile"></div>
            <img src="https://media.licdn.com/mpr/mpr/shrinknp_400_400/AAEAAQAAAAAAAAphAAAAJDk4YmJhYTg2LTM5ZGItNDI5Ny05MjU3LTBjM2NiNzlmZjczMw.jpg" class="thumb-lg img-circle img-thumbnail" alt="img">
            <h4>Marcus Vinícius Campos</h4>
            <p class="text-muted"><i class="fa fa-map-marker"></i> Minas Gerais</p>
            <a href="https://github.com/marcus-campos" class="btn btn-sm btn-github m-t-20"><i class="fa fa-github" aria-hidden="true"></i> GitHub</a>
            <a href="https://www.linkedin.com/in/marcusviniciuscampos/" class="btn btn-sm btn-linkedin m-t-20"><i class="fa fa fa-linkedin" aria-hidden="true"></i> LinkedIn</a>
            <p class="m-t-10 text-muted p-20">

            </p>
        </div>
    </div>
</div>